package it.unicam.tcpimpact.graph;
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.CompactConstructorDeclaration;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.ast.body.EnumDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.Parameter;
import com.github.javaparser.ast.body.RecordDeclaration;
import com.github.javaparser.ast.expr.AnnotationExpr;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.MethodReferenceExpr;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.ast.nodeTypes.modifiers.NodeWithPrivateModifier;
import com.github.javaparser.ast.nodeTypes.modifiers.NodeWithProtectedModifier;
import com.github.javaparser.ast.nodeTypes.modifiers.NodeWithPublicModifier;
import com.github.javaparser.ast.type.ClassOrInterfaceType;
import it.unicam.tcpimpact.coverage.JacocoXmlCoverageParser;
import it.unicam.tcpimpact.graph.model.CallKind;
import it.unicam.tcpimpact.graph.model.ChangeStatus;
import it.unicam.tcpimpact.graph.model.ImpactEdge;
import it.unicam.tcpimpact.graph.model.ImpactGraph;
import it.unicam.tcpimpact.graph.model.MethodNode;
import it.unicam.tcpimpact.graph.model.MethodNodeType;
import it.unicam.tcpimpact.model.ChangedMethod;
import it.unicam.tcpimpact.model.MethodId;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/**
 * Builds a directed method-level impact graph. Every edge points in the direction risk can propagate.
 */
public class ImpactGraphBuilder {
    // only annotated methods in src/test/java become TEST_METHOD nodes
    private static final Set<String> TEST_ANNOTATIONS = Set.of(
            "Test",
            "org.junit.Test",
            "org.junit.jupiter.api.Test",
            "ParameterizedTest",
            "org.junit.jupiter.params.ParameterizedTest",
            "RepeatedTest",
            "org.junit.jupiter.api.RepeatedTest"
    );

    private final ParserFactory factory;

    public ImpactGraphBuilder(ParserFactory factory) {
        this.factory = factory;
    }

    /**
     * Orchestrates graph construction.
     *
     * @param repositoryPath path of the repository
     * @param projectPath path of the project, relatively to the repository
     * @param changedMethods methods changed
     * @param coverageReports coverage reports generated by JaCoCo
     * @return the full impact graph
     * @throws IOException if project sources or coverage reports cannot be read
     */
    public ImpactGraph build(Path repositoryPath, Path projectPath, Collection<ChangedMethod> changedMethods, Collection<Path> coverageReports)
            throws IOException {
        ParsedProject parsedProject = parseProject(repositoryPath, projectPath);

        // keep both exact and loose id. JavaParser resolution may use qualified type names
        Map<MethodId, ParsedMethod> methodsById = new LinkedHashMap<>();
        Map<String, MethodId> looseIds = new HashMap<>();
        for(ParsedMethod method : parsedProject.methods()){
            methodsById.put(method.node().id(), method);
            looseIds.putIfAbsent(methodKey(method.node().id()), method.node().id());
        }

        // changed methods seed risk
        ChangeIndex changeIndex = ChangeIndex.from(changedMethods);
        Map<MethodId, MethodNode> nodesById = new LinkedHashMap<>();
        for(ParsedMethod method : parsedProject.methods()){
            MethodNode node = method.node();
            Optional<ChangedMethod> changedMethod = changeIndex.find(node.id());
            if(changedMethod.isEmpty()){
                changedMethod = changeIndex.findLoose(node.id());
            }
            if(changedMethod.isPresent()){
                node = node.withChange(ChangeStatus.MODIFIED, changedMethod.get().changedLines(), 1.0);
            }
            nodesById.put(node.id(), node);
        }

        // external calls are kept as caller metadata; they do not become propagation nodes
        EdgeExtraction extractedCalls = collectCallImpacts(parsedProject.methods(), methodsById.keySet(), looseIds);
        nodesById = attachExternalCalls(nodesById, extractedCalls.externalCalls());

        Set<ImpactEdge> edges = new LinkedHashSet<>();
        edges.addAll(extractedCalls.edges());
        edges.addAll(collectContractImpacts(parsedProject));
        edges.addAll(collectCoverageImpacts(coverageReports, nodesById.values()));

        return new ImpactGraph(new LinkedHashSet<>(nodesById.values()), edges);
    }

    private ParsedProject parseProject(Path repositoryPath, Path projectPath) throws IOException {
        // parse main and test source roots with the same symbol solver so tests can resolve project methods
        List<Path> sourceRoots = ProjectJavaSources.existingJavaRoots(repositoryPath, projectPath);
        JavaParser parser = factory.create(sourceRoots);
        List<ParsedMethod> methods = new ArrayList<>();
        Map<String, TypeInfo> types = new LinkedHashMap<>();

        for(Path sourceRoot : sourceRoots){
            boolean testSource = sourceRoot.equals(ProjectJavaSources.testJavaRoot(repositoryPath, projectPath));
            for(Path javaFile : ProjectJavaSources.listJavaFiles(sourceRoot)){
                ParseResult<CompilationUnit> parseResult = parser.parse(javaFile);
                if(parseResult.getResult().isEmpty()){
                    System.out.println("Unable to parse " + javaFile);
                    continue;
                }
                CompilationUnit compilationUnit = parseResult.getResult().get();
                String packageName = compilationUnit.getPackageDeclaration()
                        .map(declaration -> declaration.getNameAsString())
                        .orElse("");
                Path relativePath = ProjectJavaSources.repositoryRelativePath(repositoryPath, javaFile);
                collectTypes(compilationUnit, packageName, types);
                collectMethods(compilationUnit, packageName, relativePath, testSource, methods);
            }
        }

        return new ParsedProject(methods, types);
    }

    private void collectTypes(CompilationUnit compilationUnit, String packageName, Map<String, TypeInfo> types) {
        for(ClassOrInterfaceDeclaration typeDeclaration : compilationUnit.findAll(ClassOrInterfaceDeclaration.class)){
            String className = resolveTypeDeclarationName(typeDeclaration);
            if(className.isBlank()){
                continue;
            }
            String qualifiedName = qualifiedTypeName(packageName, className);
            TypeInfo typeInfo = new TypeInfo(
                    packageName,
                    className,
                    qualifiedName,
                    typeDeclaration.isInterface(),
                    typeDeclaration.isAbstract(),
                    resolveTypeNames(typeDeclaration.getExtendedTypes()),
                    resolveTypeNames(typeDeclaration.getImplementedTypes())
            );
            types.put(qualifiedName, typeInfo);
            types.putIfAbsent(className, typeInfo);
            types.putIfAbsent(typeDeclaration.getNameAsString(), typeInfo);
        }
    }

    private List<String> resolveTypeNames(List<ClassOrInterfaceType> types) {
        List<String> result = new ArrayList<>();
        for(ClassOrInterfaceType type : types){
            result.add(type.getNameWithScope());
            try {
                result.add(type.resolve().asReferenceType().getQualifiedName());
            } catch (RuntimeException ignored) {
                // keep the source spelling above as a fallback
            }
        }
        return result.stream().distinct().toList();
    }

    private void collectMethods(
            CompilationUnit compilationUnit,
            String packageName,
            Path relativePath,
            boolean testSource,
            List<ParsedMethod> methods
    ) {
        for(MethodDeclaration methodDeclaration : compilationUnit.findAll(MethodDeclaration.class)){
            toParsedMethod(methodDeclaration, packageName, relativePath, testSource).ifPresent(methods::add);
        }
        for(ConstructorDeclaration constructorDeclaration : compilationUnit.findAll(ConstructorDeclaration.class)){
            toParsedConstructor(constructorDeclaration, packageName, relativePath, testSource).ifPresent(methods::add);
        }
        for(CompactConstructorDeclaration compactConstructorDeclaration : compilationUnit.findAll(CompactConstructorDeclaration.class)){
            toParsedCompactConstructor(compactConstructorDeclaration, packageName, relativePath, testSource).ifPresent(methods::add);
        }
    }

    private Optional<ParsedMethod> toParsedMethod(MethodDeclaration declaration, String packageName, Path relativePath, boolean testSource) {
        if(declaration.getBegin().isEmpty() || declaration.getEnd().isEmpty()){
            return Optional.empty();
        }
        String className = resolveClassName(declaration);
        if(className.isBlank()){
            return Optional.empty();
        }
        MethodId methodId = resolveMethod(declaration)
                .orElseGet(() -> astMethodId(packageName, className, declaration.getNameAsString(), declaration.getParameters(), declaration.getType().asString()));
        boolean inInterface = isInInterface(declaration);
        boolean testMethod = testSource && hasAnyAnnotation(declaration, TEST_ANNOTATIONS);
        // non-annotated methods under src/test/java stay as TEST_SUPPORT_METHOD, not test cases
        MethodNodeType nodeType = methodNodeType(declaration, testSource, testMethod, inInterface);
        MethodNode node = new MethodNode(
                methodId,
                nodeType,
                methodId.packageName(),
                methodId.className(),
                methodId.methodName(),
                methodId.toString(),
                methodId.returnType(),
                relativePath.toString(),
                declaration.getBegin().get().line,
                declaration.getEnd().get().line,
                visibility(declaration),
                methodKind(nodeType),
                declaration.isStatic(),
                declaration.isAbstract() || nodeType == MethodNodeType.INTERFACE_METHOD,
                inInterface,
                false,
                testMethod,
                ChangeStatus.UNCHANGED,
                List.of(),
                0.0,
                0.0,
                List.of()
        );
        return Optional.of(new ParsedMethod(node, declaration, qualifiedTypeName(packageName, className), testSource));
    }

    private Optional<ParsedMethod> toParsedConstructor(ConstructorDeclaration declaration, String packageName, Path relativePath, boolean testSource) {
        if(declaration.getBegin().isEmpty() || declaration.getEnd().isEmpty()){
            return Optional.empty();
        }
        String className = resolveClassName(declaration);
        if(className.isBlank()){
            return Optional.empty();
        }
        MethodId methodId = resolveConstructor(declaration)
                .orElseGet(() -> astMethodId(packageName, className, MethodId.CONSTRUCTOR_NAME, declaration.getParameters(), ""));
        MethodNode node = constructorNode(methodId, relativePath, declaration.getBegin().get().line, declaration.getEnd().get().line, visibility(declaration), "constructor", isInInterface(declaration), testSource);
        return Optional.of(new ParsedMethod(node, declaration, qualifiedTypeName(packageName, className), testSource));
    }

    private Optional<ParsedMethod> toParsedCompactConstructor(CompactConstructorDeclaration declaration, String packageName, Path relativePath, boolean testSource) {
        if(declaration.getBegin().isEmpty() || declaration.getEnd().isEmpty()){
            return Optional.empty();
        }
        String className = resolveClassName(declaration);
        if(className.isBlank()){
            return Optional.empty();
        }
        MethodId methodId = new MethodId(packageName, className, MethodId.CONSTRUCTOR_NAME, List.of(), "");
        MethodNode node = constructorNode(methodId, relativePath, declaration.getBegin().get().line, declaration.getEnd().get().line, "package-private", "compact_constructor", isInInterface(declaration), testSource);
        return Optional.of(new ParsedMethod(node, declaration, qualifiedTypeName(packageName, className), testSource));
    }

    private MethodNode constructorNode(
            MethodId methodId,
            Path relativePath,
            int startLine,
            int endLine,
            String visibility,
            String methodKind,
            boolean inInterface,
            boolean testSource
    ) {
        return new MethodNode(
                methodId,
                MethodNodeType.CONSTRUCTOR_METHOD,
                methodId.packageName(),
                methodId.className(),
                methodId.methodName(),
                methodId.toString(),
                "",
                relativePath.toString(),
                startLine,
                endLine,
                visibility,
                methodKind,
                false,
                false,
                inInterface,
                true,
                false,
                ChangeStatus.UNCHANGED,
                List.of(),
                0.0,
                0.0,
                List.of()
        );
    }

    private MethodNodeType methodNodeType(MethodDeclaration declaration, boolean testSource, boolean testMethod, boolean inInterface) {
        if(testMethod){
            return MethodNodeType.TEST_METHOD;
        }
        if(testSource){
            return MethodNodeType.TEST_SUPPORT_METHOD;
        }
        if(inInterface && declaration.getBody().isPresent()){
            return MethodNodeType.DEFAULT_INTERFACE_METHOD;
        }
        if(inInterface){
            return MethodNodeType.INTERFACE_METHOD;
        }
        if(declaration.isAbstract()){
            return MethodNodeType.ABSTRACT_METHOD;
        }
        return MethodNodeType.METHOD;
    }

    private String methodKind(MethodNodeType nodeType) {
        return switch (nodeType) {
            case TEST_METHOD -> "test";
            case TEST_SUPPORT_METHOD -> "test_support";
            case ABSTRACT_METHOD -> "abstract";
            case INTERFACE_METHOD -> "interface";
            case DEFAULT_INTERFACE_METHOD -> "default_interface";
            case CONSTRUCTOR_METHOD -> "constructor";
            case METHOD -> "method";
        };
    }

    private EdgeExtraction collectCallImpacts(Collection<ParsedMethod> methods, Set<MethodId> projectMethods, Map<String, MethodId> looseIds) {
        Set<ImpactEdge> edges = new LinkedHashSet<>();
        Map<MethodId, Set<String>> externalCalls = new LinkedHashMap<>();

        for(ParsedMethod parsedMethod : methods){
            MethodId caller = parsedMethod.node().id();
            for(MethodCallExpr expression : parsedMethod.declaration().findAll(MethodCallExpr.class)){
                Optional<MethodId> callee = resolveMethodCall(expression)
                        .flatMap(methodId -> projectMethodId(methodId, projectMethods, looseIds));
                if(callee.isPresent()){
                    CallKind callKind = callKind(expression, callee.get(), methods);
                    edges.add(ImpactEdge.callImpact(callee.get(), caller, callKind));
                } else {
                    addExternalCall(externalCalls, caller, expression.toString());
                }
            }

            for(MethodReferenceExpr expression : parsedMethod.declaration().findAll(MethodReferenceExpr.class)){
                Optional<MethodId> callee = resolveMethodReference(expression)
                        .flatMap(methodId -> projectMethodId(methodId, projectMethods, looseIds));
                if(callee.isPresent()){
                    edges.add(ImpactEdge.callImpact(callee.get(), caller, CallKind.METHOD_REFERENCE));
                } else {
                    addExternalCall(externalCalls, caller, expression.toString());
                }
            }

            for(ObjectCreationExpr expression : parsedMethod.declaration().findAll(ObjectCreationExpr.class)){
                Optional<MethodId> constructor = resolveConstructorCall(expression)
                        .flatMap(methodId -> projectMethodId(methodId, projectMethods, looseIds));
                if(constructor.isPresent()){
                    // constructor calls stay CALL_IMPACT edges and are distinguished by callKind
                    edges.add(ImpactEdge.callImpact(constructor.get(), caller, CallKind.CONSTRUCTOR));
                } else {
                    addExternalCall(externalCalls, caller, "new " + expression.getType().asString());
                }
            }
        }

        return new EdgeExtraction(edges, externalCalls);
    }

    private Optional<MethodId> projectMethodId(MethodId candidate, Set<MethodId> projectMethods, Map<String, MethodId> looseIds) {
        if(projectMethods.contains(candidate)){
            return Optional.of(candidate);
        }
        return Optional.ofNullable(looseIds.get(methodKey(candidate)));
    }

    private CallKind callKind(MethodCallExpr expression, MethodId callee, Collection<ParsedMethod> methods) {
        if(expression.getScope().map(scope -> scope.toString().equals("super")).orElse(false)){
            return CallKind.SUPER;
        }
        for(ParsedMethod method : methods){
            if(method.node().id().equals(callee) && "private".equals(method.node().visibility())){
                return CallKind.PRIVATE;
            }
        }
        return CallKind.NORMAL;
    }

    private void addExternalCall(Map<MethodId, Set<String>> externalCalls, MethodId caller, String call) {
        externalCalls.computeIfAbsent(caller, ignored -> new LinkedHashSet<>()).add(call);
    }

    private Map<MethodId, MethodNode> attachExternalCalls(Map<MethodId, MethodNode> nodesById, Map<MethodId, Set<String>> externalCalls) {
        Map<MethodId, MethodNode> result = new LinkedHashMap<>();
        for(Map.Entry<MethodId, MethodNode> entry : nodesById.entrySet()){
            Set<String> calls = externalCalls.getOrDefault(entry.getKey(), Set.of());
            result.put(entry.getKey(), entry.getValue().withExternalCalls(calls.stream().sorted().toList()));
        }
        return result;
    }

    private Set<ImpactEdge> collectContractImpacts(ParsedProject parsedProject) {
        Set<ImpactEdge> edges = new LinkedHashSet<>();
        Map<String, Set<String>> typeAncestors = buildTypeAncestors(parsedProject.types());

        for(ParsedMethod contractMethod : parsedProject.methods()){
            MethodNode source = contractMethod.node();
            if(!isContractNode(source)){
                continue;
            }
            for(ParsedMethod implementation : parsedProject.methods()){
                MethodNode target = implementation.node();
                if(source.id().equals(target.id()) || !canImplementContract(target)){
                    continue;
                }
                Set<String> ancestors = typeAncestors.getOrDefault(implementation.declaringTypeName(), Set.of());
                if(ancestors.contains(contractMethod.declaringTypeName()) && compatibleSignature(source.id(), target.id())){
                    // one-way: contract/abstract/interface method -> overriding implementation
                    edges.add(ImpactEdge.contractImpact(source.id(), target.id()));
                }
            }
        }

        return edges;
    }

    private boolean isContractNode(MethodNode node) {
        return node.nodeType() == MethodNodeType.ABSTRACT_METHOD
                || node.nodeType() == MethodNodeType.INTERFACE_METHOD
                || node.nodeType() == MethodNodeType.DEFAULT_INTERFACE_METHOD;
    }

    private boolean canImplementContract(MethodNode node) {
        return node.nodeType() == MethodNodeType.METHOD
                || node.nodeType() == MethodNodeType.TEST_SUPPORT_METHOD
                || node.nodeType() == MethodNodeType.TEST_METHOD;
    }

    private Map<String, Set<String>> buildTypeAncestors(Map<String, TypeInfo> types) {
        Map<String, Set<String>> ancestors = new LinkedHashMap<>();
        for(TypeInfo type : new LinkedHashSet<>(types.values())){
            Set<String> visited = new LinkedHashSet<>();
            ArrayDeque<String> queue = new ArrayDeque<>();
            queue.addAll(type.extendedTypes());
            queue.addAll(type.implementedTypes());

            while(!queue.isEmpty()){
                String current = queue.removeFirst();
                TypeInfo ancestor = types.get(current);
                String normalized = ancestor == null ? current : ancestor.qualifiedName();
                if(!visited.add(normalized)){
                    continue;
                }
                if(ancestor != null){
                    queue.addAll(ancestor.extendedTypes());
                    queue.addAll(ancestor.implementedTypes());
                }
            }
            ancestors.put(type.qualifiedName(), visited);
        }
        return ancestors;
    }

    private boolean compatibleSignature(MethodId contract, MethodId implementation) {
        return contract.methodName().equals(implementation.methodName())
                && simpleParameterTypes(contract).equals(simpleParameterTypes(implementation));
    }

    private Set<ImpactEdge> collectCoverageImpacts(Collection<Path> coverageReports, Collection<MethodNode> nodes) throws IOException {
        if(coverageReports == null || coverageReports.isEmpty()){
            return Set.of();
        }
        Set<ImpactEdge> edges = new LinkedHashSet<>();
        JacocoXmlCoverageParser parser = new JacocoXmlCoverageParser();
        for(Path coverageReport : coverageReports){
            edges.addAll(parser.parse(coverageReport, nodes));
        }
        return edges;
    }

    private Optional<MethodId> resolveMethod(MethodDeclaration declaration) {
        try {
            return Optional.of(ResolvedMethodIds.from(declaration.resolve()));
        } catch (RuntimeException exception) {
            return Optional.empty();
        }
    }

    private Optional<MethodId> resolveConstructor(ConstructorDeclaration declaration) {
        try {
            return Optional.of(ResolvedMethodIds.from(declaration.resolve()));
        } catch (RuntimeException exception) {
            return Optional.empty();
        }
    }

    private Optional<MethodId> resolveMethodCall(MethodCallExpr expression) {
        try {
            return Optional.of(ResolvedMethodIds.from(expression.resolve()));
        } catch (RuntimeException exception) {
            return Optional.empty();
        }
    }

    private Optional<MethodId> resolveMethodReference(MethodReferenceExpr expression) {
        try {
            return Optional.of(ResolvedMethodIds.from(expression.resolve()));
        } catch (RuntimeException exception) {
            return Optional.empty();
        }
    }

    private Optional<MethodId> resolveConstructorCall(ObjectCreationExpr expression) {
        try {
            return Optional.of(ResolvedMethodIds.from(expression.resolve()));
        } catch (RuntimeException exception) {
            return Optional.empty();
        }
    }

    private MethodId astMethodId(String packageName, String className, String methodName, List<Parameter> parameters, String returnType) {
        return new MethodId(packageName, className, methodName, parameters.stream().map(parameter -> parameter.getType().asString()).toList(), returnType);
    }

    private String resolveClassName(Node node) {
        List<String> classNames = new ArrayList<>();
        Node currentNode = node;
        while(currentNode.getParentNode().isPresent()){
            currentNode = currentNode.getParentNode().get();
            switch (currentNode) {
                case ClassOrInterfaceDeclaration declaration -> classNames.add(declaration.getNameAsString());
                case EnumDeclaration declaration -> classNames.add(declaration.getNameAsString());
                case RecordDeclaration declaration -> classNames.add(declaration.getNameAsString());
                default -> {
                }
            }
        }
        Collections.reverse(classNames);
        return String.join(".", classNames);
    }

    private String resolveTypeDeclarationName(ClassOrInterfaceDeclaration typeDeclaration) {
        List<String> classNames = new ArrayList<>();
        classNames.add(typeDeclaration.getNameAsString());
        Node currentNode = typeDeclaration;
        while(currentNode.getParentNode().isPresent()){
            currentNode = currentNode.getParentNode().get();
            switch (currentNode) {
                case ClassOrInterfaceDeclaration declaration -> classNames.add(declaration.getNameAsString());
                case EnumDeclaration declaration -> classNames.add(declaration.getNameAsString());
                case RecordDeclaration declaration -> classNames.add(declaration.getNameAsString());
                default -> {
                }
            }
        }
        Collections.reverse(classNames);
        return String.join(".", classNames);
    }

    private boolean isInInterface(Node node) {
        return nearestType(node)
                .filter(ClassOrInterfaceDeclaration::isInterface)
                .isPresent();
    }

    private Optional<ClassOrInterfaceDeclaration> nearestType(Node node) {
        Node currentNode = node;
        while(currentNode.getParentNode().isPresent()){
            currentNode = currentNode.getParentNode().get();
            if(currentNode instanceof ClassOrInterfaceDeclaration declaration){
                return Optional.of(declaration);
            }
        }
        return Optional.empty();
    }

    private String visibility(Node node) {
        if(node instanceof NodeWithPublicModifier<?> publicModifier && publicModifier.isPublic()){
            return "public";
        }
        if(node instanceof NodeWithProtectedModifier<?> protectedModifier && protectedModifier.isProtected()){
            return "protected";
        }
        if(node instanceof NodeWithPrivateModifier<?> privateModifier && privateModifier.isPrivate()){
            return "private";
        }
        return "package-private";
    }

    private boolean hasAnyAnnotation(Node node, Set<String> annotationNames) {
        return node.findAll(AnnotationExpr.class)
                .stream()
                .map(AnnotationExpr::getNameAsString)
                .anyMatch(name -> annotationNames.contains(name) || annotationNames.contains(simpleName(name)));
    }

    private String qualifiedTypeName(String packageName, String className) {
        if(packageName == null || packageName.isBlank()){
            return className;
        }
        return packageName + "." + className;
    }

    private String methodKey(MethodId methodId) {
        return methodId.packageName() + "#"
                + methodId.className() + "#"
                + methodId.methodName() + "#"
                + String.join(",", simpleParameterTypes(methodId));
    }

    private List<String> simpleParameterTypes(MethodId methodId) {
        return methodId.parameterTypes()
                .stream()
                .map(ImpactGraphBuilder::simpleTypeName)
                .toList();
    }

    private static String simpleTypeName(String type) {
        if(type == null || type.isBlank()){
            return "";
        }
        String withoutGenerics = type.replaceAll("<.*>", "");
        int arrayIndex = withoutGenerics.indexOf("[]");
        String arraySuffix = arrayIndex >= 0 ? withoutGenerics.substring(arrayIndex) : "";
        String base = arrayIndex >= 0 ? withoutGenerics.substring(0, arrayIndex) : withoutGenerics;
        int dot = base.lastIndexOf('.');
        return (dot >= 0 ? base.substring(dot + 1) : base) + arraySuffix;
    }

    private String simpleName(String name) {
        int dot = name.lastIndexOf('.');
        return dot >= 0 ? name.substring(dot + 1) : name;
    }

    private record ParsedProject(List<ParsedMethod> methods, Map<String, TypeInfo> types) { }

    private record ParsedMethod(MethodNode node, Node declaration, String declaringTypeName, boolean testSource) { }

    private record TypeInfo(
            String packageName,
            String className,
            String qualifiedName,
            boolean isInterface,
            boolean isAbstract,
            List<String> extendedTypes,
            List<String> implementedTypes
    ) { }

    private record EdgeExtraction(Set<ImpactEdge> edges, Map<MethodId, Set<String>> externalCalls) { }

    private record ChangeIndex(Map<MethodId, ChangedMethod> exact, Map<String, ChangedMethod> loose) {
        static ChangeIndex from(Collection<ChangedMethod> changedMethods) {
            if(changedMethods == null || changedMethods.isEmpty()){
                return new ChangeIndex(Map.of(), Map.of());
            }
            Map<MethodId, ChangedMethod> exact = new LinkedHashMap<>();
            Map<String, ChangedMethod> loose = new LinkedHashMap<>();
            for(ChangedMethod changedMethod : changedMethods){
                exact.put(changedMethod.methodRange().methodId(), changedMethod);
                loose.put(methodKeyStatic(changedMethod.methodRange().methodId()), changedMethod);
            }
            return new ChangeIndex(exact, loose);
        }

        Optional<ChangedMethod> find(MethodId methodId) {
            return Optional.ofNullable(exact.get(methodId));
        }

        Optional<ChangedMethod> findLoose(MethodId methodId) {
            return Optional.ofNullable(loose.get(methodKeyStatic(methodId)));
        }

        private static String methodKeyStatic(MethodId methodId) {
            return methodId.packageName() + "#"
                    + methodId.className() + "#"
                    + methodId.methodName() + "#"
                    + String.join(",", methodId.parameterTypes().stream().map(ImpactGraphBuilder::simpleTypeName).toList());
        }
    }
}
